baseURL = "https://prabhumarappan.github.io/"
languageCode = "en-us"
title = "Prabhu Marappan"
theme="hugo-developer-portfolio"


[menu]
  [[menu.main]]
  name = "About"
  URL = "about"
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  [[menu.main]]
  name = "Contact"
  URL = "contact"


[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "Prabhu Marappan, Backend Software Engineer with 4 years of work experience!"
author = "Prabhu Marappan"


  [params.footer]
  email = "prabhum.794@gmail.com"
  address = "Bengaluru, India"
  googlemaps = ""

